# T3 MakeFile
#
server.o : T3Server.cpp Socket.cpp ProtocolHandler.cpp GameManager.cpp Game.cpp \
	Player.cpp 
	g++ T3Server.cpp Socket.cpp ProtocolHandler.cpp GameManager.cpp Game.cpp Player.cpp -lpthread -o server.o
